<?php
/**
 * Created by PhpStorm.
 * User: austi_000
 * Date: 5/31/2016
 * Time: 9:05 AM
 */

namespace App\Repositories;
use Illuminate\Support\Facades\Auth;

class OrderRepository extends BaseRepository
{
	/**
	 * @param $slug
	 * @param array $columns
	 * @return mixed
	 */
	public function findBySlug($slug, $columns = ['*'])
	{
		if($slug == "open")
			return $this->model
				->where('executed',0)
				->where('failed',0)
				->where('user_id',Auth::user()->id)
				->firstOrFail();
		return parent::findBySlug($slug, $columns); // TODO: Change the autogenerated stub
	}
}
